### ISSUE TITLE
Idea: Concrete Problem. Trust Graph for Kubernetes

### ISSUE THREAD

**Issue by dlorenc** [ossf/wg-supply-chain-integrity#20]
I'm heavily influenced by the cloud native bubble I've been stuck in for the last few years, but this struck me as maybe a fun challenge to continue understanding the scope of the problem.

What if we tried to document the trust graph of installing a Kubernetes cluster. We could pick an install method/provider/distribution, and try to determine every organization/entity/individual that we're "trusting" to have acted responsibly on the way.

The point would be explicitly not to show which distribution is "best", but to show how hard this is to do in practice at all, and to look for ways to make this easier.

I'm aware this is a very CNCF-y problem and there are dozens of other areas (mobile, web, embedded, etc.) where this is arguably harder and more important. This just happpens to be the one I'm most familiar with. Consider this example as a straw person. 

I think of this kind of like the "what happens when you press foo.bar.com on your keyboard in a browser and press enter" interview question. 

If we were able to produce a GitHub repository like https://github.com/alex/what-happens-when  but for "kubeadm init" I would consider it a huge success :)

**Comment by dlorenc** [comment]
I've started poking around with this, starting with the container images. Here's what I've found so far:

- Releases are all tracked in an issue. Example: https://github.com/kubernetes/sig-release/issues/1249
- Images live in k8s.gcr.io
- Only a "promoter" has permission to push here: https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io
- Developers push to staging locations and use PRs to move images to the real location
  - Example PR: https://github.com/kubernetes/k8s.io/commit/4d96bf49f0a53363a98bf20b09cb792231716cf2
- No way to see how the image was built. Logs are in the PR, but they're private: https://github.com/kubernetes/k8s.io/pull/1269
- Trying to find Dockerfiles/bazel rules for the images still, haven't found them yet
- Binaries have checksums published, no signatures
  - Checksums stored right next to binaries: https://github.com/kubernetes/sig-release/tree/master/release-engineering

**Comment by dlorenc** [comment]
A couple other things:

Kubeadm itself is distributed via apt: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl

The repo is at https://packages.cloud.google.com, and the keys are available here: https://packages.cloud.google.com/apt/doc/apt-key.gpg

Next up - setting up a cluster with kubeadm and getting a list of all running images.

**Comment by dlorenc** [comment]
Here are the defaults for the latest kubeadm:

```shell
# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:47:53Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
root@kubeadm:/home/dlorenc# kubeadm config images list
k8s.gcr.io/kube-apiserver:v1.19.3
k8s.gcr.io/kube-controller-manager:v1.19.3
k8s.gcr.io/kube-scheduler:v1.19.3
k8s.gcr.io/kube-proxy:v1.19.3
k8s.gcr.io/pause:3.2
k8s.gcr.io/etcd:3.4.13-0
k8s.gcr.io/coredns:1.7.0
```

Everything here is pulled by tag.

**Comment by dlorenc** [comment]
The digests for most of these images are present in the yaml checked into github: 
https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/images/k8s-staging-kubernetes/images.yaml

etcd and coredns aren't in that file, they have their own:
https://github.com/kubernetes/k8s.io/blob/76b402bc5e5c6bd186249179bd55bc3e6e8ba961/k8s.gcr.io/images/k8s-staging-coredns/images.yaml for coredns

https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/images/k8s-staging-etcd/images.yaml for etcd

**Comment by dlorenc** [comment]
This little script verifies the images on a running node against the repo by making sure every digest is present in the repo:

```shell
images=$(docker images -q | xargs docker inspect | jq -r ".[].RepoDigests[0]")
for image in $images; do
  echo $image;
  dgst=$(echo $image | cut -d'@' -f2);
  grep -rl $dgst k8s.io/k8s.gcr.io/images;
done
```

**Comment by dlorenc** [comment]
Next step: figure out what's in all those container images and where it came from.

**Comment by joshuagl** [comment]
For generally understanding the contents of a container image, the open source tool [tern](https://github.com/tern-tools/tern) (disclaimer: colleagues maintain this tool) is good at reading an increasingly large selection of package manager databases that exist in an image (in order to determine the images contents) and generating an SBoM. The caveat for Tern is that it currently requires the image contain both the package manager tool and the package manager database.

I believe that Kubernetes images ~recently switched to using [distroless](https://github.com/GoogleContainerTools/distroless) images. The downside of that change is that distroless images are more difficult to introspect with open source tools like tern because they don't include the package tool or the package manager database in a standard format. 

However the upside is that distroless images – through being built with Bazel, and using Debian snapshot repositories – are deterministically produced. With a bit of reading over the Bazel build files I was able to identify the precise Debian packages included in the container images with relative ease and not too many assumptions (i.e. mapping hashes in the distroless tags to commits in the distroless repository).

Assuming there are contents added on top of the distroless base image, it may be more difficult to determine exactly what sources correspond to those contents. If the base distroless image is pulled in with the `FROM` line in a Dockerfile, that's unlikely to be deterministic (unless the Dockerfile author was trying very hard to make the image reproducible).
If the final image is produced using the Bazel rules or some other deterministic process, this may be easier.

**Comment by ghindman** [comment]
I will 2nd that Tern has a lot a of promise, and is sorely needed, but I don't know that it applies here.  Given that anyone grabbing a container that is not using fixed tags/layers is going to get a slightly different mix of SW - eg., every time I do a docker pull ubuntu:focal I'm getting the released tip of 20.04, not a static version - SBOM info will likely have to come from the instantiated SW in the container at runtime just as though it were a normal running system.

**Comment by dlorenc** [comment]
> I believe that Kubernetes images ~recently switched to using [distroless](https://github.com/GoogleContainerTools/distroless) images. The downside of that change is that distroless images are more difficult to introspect with open source tools like tern because they don't include the package tool or the package manager database in a standard format.

Correct. Distroless (well technically the bazel package rules) install packages from Debian repos using apt. They generate "exploded" manifest files which are basically the same format as apt, but one package per file instead of one combined file.

We've added support for this structure in Google's container analysis system, @joshuagl do you happen to know if tern might be willing to add this support too? I can dig up more details.

**Comment by joshuagl** [comment]
> > I believe that Kubernetes images ~recently switched to using [distroless](https://github.com/GoogleContainerTools/distroless) images. The downside of that change is that distroless images are more difficult to introspect with open source tools like tern because they don't include the package tool or the package manager database in a standard format.
> 
> Correct. Distroless (well technically the bazel package rules) install packages from Debian repos using apt. They generate "exploded" manifest files which are basically the same format as apt, but one package per file instead of one combined file.

Right, I was pointed at `/var/lib/dpkg/status.d/` in a distroless image recently and thinking about how this might work.

> We've added support for this structure in Google's container analysis system, @joshuagl do you happen to know if tern might be willing to add this support too? I can dig up more details.

I believe the Tern maintainers would be interested in adding support for distroless images, but let's invite them here and ask cc @nishakm @rnjudge

**Comment by nishakm** [comment]
@dlorenc @joshuagl, we can definitely add support for Distroless images if you can provide a script to parse `/var/lib/dpkg/status.d/` (I can also take a look at it offline).

On the subject of the things on top of Distroless
```
k8s.gcr.io/kube-apiserver:v1.19.3
k8s.gcr.io/kube-controller-manager:v1.19.3
k8s.gcr.io/kube-scheduler:v1.19.3
k8s.gcr.io/kube-proxy:v1.19.3
k8s.gcr.io/pause:3.2
k8s.gcr.io/etcd:3.4.13-0
k8s.gcr.io/coredns:1.7.0
```
This is harder as things like coredns and etcd are golang binary blobs that are statically compiled on top of `docker.io/library/golang` and that may or may not be tagged. Tern can use an external static analyzer to look at the binary blob strings but you will only get the urls for those projects. After that it's hit or miss  whether the tag of the container image above corresponds to a git release tag on the repo.

**Comment by dlorenc** [comment]
Sorry for the delay - @nishakm I'd be happy to provide this script. I think it's literally as easy as just concatenating the files then parsing as a standard /var/lib/dpkg/status file.

Do you have a pointer to where this script would go/how it would be integrated that I could reference?

**Comment by nishakm** [comment]
> Sorry for the delay - @nishakm I'd be happy to provide this script. I think it's literally as easy as just concatenating the files then parsing as a standard /var/lib/dpkg/status file.
> 
> Do you have a pointer to where this script would go/how it would be integrated that I could reference?

Scripts go in here: https://github.com/tern-tools/tern/tree/master/tern/scripts
You can create a folder called `distroless` here.

The script gets called from here: https://github.com/tern-tools/tern/blob/master/tern/analyze/default/command_lib/base.yml

You can make a new listing like this:
```
dpkg: <-- any canonical file in the distroless rootfs
  pkg_format: 'deb'
  os_guess:
    - 'Distroless'
  path:
    - 'possible/paths/to/canonical/file'
  pkg_separators:
    - '='
  pinning_separator: '='
  # either enter the package names as a list or a snippet to invoke either within or outside the container
  names:
    invoke:
      1:
        # Currently two types of environments are supported - host or container
        host:
          - "invoke/script/for/listing/package/names.sh"
    delimiter: "\n" <-- just an indication of how to split all the names
  # the length of this list should be the same as the names or else there will be a mismatch
  versions:
    invoke:
      1:
        host:
          - "invoke/script/for/listing/package/versions.sh"
    delimiter: "\n"
  copyrights:
    invoke:
      1:
        host:
          - "invoke/script/for/listing/package/copyrights.sh"
    delimiter: 'LICF'
  files:
    invoke:
      1:
        host:
        - "invoke/script/for/listing/package/licenses.sh"
    delimiter: "LICF"
  proj_urls: {} (if you can find proj_urls then just add that script here too
```
You can either have separate scripts for each of the metadata or you can have one script with command line options. It's up to you. Let me know if you have any questions. I look forward to your PR!
