### ISSUE TITLE
Request to add "Unexpected demise of Open Source Maintainers" under the section "Necessary Human Use Cases to Support"

### ISSUE THREAD

**Issue by nathanawmk** [ossf/wg-supply-chain-integrity#44]
Am requesting to add "Unexpected demise of Open Source Maintainers" under the section "Necessary Human Use Cases to Support". Implement a digital kill switch to deactivate account in the event that one is informed that an open source maintainer has unexpectedly passed on.

**Comment by melba-lopez** [comment]
Don't believe this to be apart of our current vision/mission. Would like to close this stale card.

@hepwori @camaleon2016 please give me a thumbs up to confirm.

**Comment by melba-lopez** [comment]
Closing this issue.  If necessary, will reopen in the future.
