### ISSUE TITLE
Applying Byzantine Fault Tolerance Algorithm to arrive at consensus to deter rogue code commits

### ISSUE THREAD

**Issue by nathanawmk** [ossf/wg-supply-chain-integrity#45]
Similar to the byzantine fault tolerance in principle, where there are _N_ replicas and _f_ of them maybe faulty (crashed/ compromised), replace _N_ with the open source maintainers and _f_ as the compromised open source maintainer, only when n = 3f+1 replicas, the code can be committed. Through such consensus mechanism, rogue code commits can be deterred. 

SOURCE:
https://www.comp.nus.edu.sg/~rahul/allfiles/cs6234-16-pbft.pdf

**Comment by melba-lopez** [comment]
Don't believe this to be apart of our current vision/mission.  Would like to close this stale card.

@hepwori @camaleon2016 please give me a thumbs up to confirm.

**Comment by camaleon2016** [comment]
Thumbs up.





Jay White (He/Him)
Security Principal Program Manager
Azure Office of the CTO
OSS Ecosystem


[Graphical user interface  Description automatically generated]

**Comment by david-a-wheeler** [comment]
This is interesting! But I don't think it applies well.

Byzantine fault models are often applied to hardware. Typically they're applied where the hardware systems are generally identical and you're trying to counter arbitrary faults which might equally occur in any of them.

This seems like a very poor analogy to software development. No one is claiming that humans are identical, in either capabilities or trustworthiness. Even if the software development is supported by AI (e.g., ChatGPT), it's the human who decides if the AI results are acceptable. Generally past performance by a human is the best available estimate for what a human will do (it's imperfect, but we know of no better method). So typical Byzantine models are mostly-wrong, as different humans *do* have different levels of trustworthiness, and it makes more sense to build on that.

Of course, reviewing results of a human is an excellent idea. But we often struggle getting just *one* more reviewer. Again, it doesn't appear that Byzantine fault models are a reasonable model of the problem (or of the solution). I'd be interested in any evidence to prove me wrong, though, it is an interesting thought experiment.

I don't see much actionable, so while the discussion might be interesting to have, it probably doesn't belong here. I'd support closing this issue, and finding some other place to have this discussion among those interested in it.
