### ISSUE TITLE
Delete all Stale Branches

### ISSUE THREAD

**Issue by melba-lopez** [ossf/wg-supply-chain-integrity#59]
@hepwori @camaleon2016 would like to cleanup old branches that have been merged or no longer apply.  Please give me a thumbs up if you approve.

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/101211710/235685678-22e4e34a-e60a-4254-b466-037cdb3eb317.png">

**Comment by melba-lopez** [comment]
Also inline with #33

**Comment by camaleon2016** [comment]
[like]  Jay White reacted to your message:
________________________________
From: Melba ***@***.***>
Sent: Tuesday, May 2, 2023 1:49:13 PM
To: ossf/wg-supply-chain-integrity ***@***.***>
Cc: Jay White ***@***.***>; Mention ***@***.***>
Subject: [ossf/wg-supply-chain-integrity] Delete all Stale Branches (Issue #59)


@hepwori<https://github.com/hepwori> @camaleon2016<https://github.com/camaleon2016> would like to cleanup old branches that have been merged or no longer apply. Please give me a thumbs up if you approve.

[image]<https://user-images.githubusercontent.com/101211710/235685678-22e4e34a-e60a-4254-b466-037cdb3eb317.png>

**Comment by camaleon2016** [comment]
Thumb up





Jay White (He/Him)
Security Principal Program Manager
Azure Office of the CTO
OSS Ecosystem


[Graphical user interface  Description automatically generated]






From: Melba ***@***.***>
Sent: Tuesday, May 2, 2023 6:49 AM
To: ossf/wg-supply-chain-integrity ***@***.***>
Cc: Jay White ***@***.***>; Mention ***@***.***>
Subject: [ossf/wg-supply-chain-integrity] Delete all Stale Branches (Issue #59)


@hepwori<https://github.com/hepwori> @camaleon2016<https://github.com/camaleon2016> would like to cleanup old branches that have been merged or no longer apply. Please give me a thumbs up if you approve.

[image]<https://user-images.githubusercontent.com/101211710/235685678-22e4e34a-e60a-4254-b466-037cdb3eb317.png>

-

**Comment by melba-lopez** [comment]
Proceeding with deleting stale branches @camaleon2016 @hepwori

**Comment by melba-lopez** [comment]
Stale Branches removed (from 3 years ago) ![image](https://github.com/ossf/wg-supply-chain-integrity/assets/101211710/785566f6-d750-4561-becf-70e6d3618f5a)
