### ISSUE TITLE
OSSF Webinar: SLSA 101 (Oct 5, 2023 @9am PST)

### ISSUE THREAD

**Issue by melba-lopez** [ossf/wg-supply-chain-integrity#71]
EPIC: https://github.com/ossf/wg-supply-chain-integrity/issues/63 

Overview: Why do i care about SLSA? _(developer persona)_

### Abstract: 

In today's interconnected digital landscape, ensuring the security and integrity of software has become more critical than ever. The rise of cyber threats and supply chain attacks has necessitated a paradigm shift in how we approach software security. The Software Bill of Materials (SBOM) initiative has gained traction, and now, a new framework is emerging as a robust solution – SLSA, or Supply Chain Levels for Software Artifacts.

Join us for an enlightening webinar as we delve into the world of SLSA and its transformative impact on software supply chain security. This session will provide a comprehensive overview of SLSA, exploring its core principles, benefits, and real-world implications for software development and deployment.

### Key Discussion Topics:

- Introduction to SLSA: Uncover its fundamental concepts and how it addresses software supply chain security challenges.
- Supply Chain Levels: Explore SLSA's framework levels and how they ensure comprehensive security throughout the supply chain.
- Trustworthiness and Transparency: Discover the mechanisms that establish trust and authenticity in software artifacts.
- Implementing SLSA: Share insights into practical strategies for integrating SLSA principles into software development processes.
- Industry Impact: Present real-world success stories of organizations benefiting from SLSA's adoption.
- Future Trends: Discuss SLSA's role in shaping the future of software supply chain security.

You can find the full abstract and further details on each of the aforementioned topics [here] https://docs.google.com/document/d/1ctvtXjYEZsxvL8k3OVGigX5aKksO6nyzCLfdLOs36dI/edit#heading=h.iteq1kboqvh6

### Participation Details: 
We will host this webinar via Zoom, and a Zoom panelist invite will be sent to your email in advance of the webinar.  We will provide graphics to you to promote on your individual social media pages, and will also tag you in social media posts before the panel date.  We will also introduce this panel to our mailing list. 

If you would like to participate, please confirm your availability for the aforementioned date and time by this upcoming **Thursday, Aug 24,** and we will provide you with further details and logistics.

**Comment by melba-lopez** [comment]
From EPIC Thoughts (to not lose track) Agenda:
Highlight OpenSSF: slsa - 10 point mobilization plan??
They are writing the code and want to use a SLSA Build
Assumes that the "build infra" already has been SLSA-fied
potential CI Tool (open source project by Mike) to call a secure builder (SLSA "Certified"); openAPI specification, which allows folks to develop plugins as they see fit
eventually we may want to have SLSA for the entire dev lifecycle, but currently focused on the build
Assume trust of the secure builder

**Comment by melba-lopez** [comment]
@jennbly FYI (to track progress/content/discussion points)

**Comment by axelsimon** [comment]
Could you clarify where this will take place, how to sign-up, etc.?

**Comment by afmarcum** [comment]
@melba-lopez Are there additional talks that this issue will cover or can it be closed for now?

The talk from October 2023 is available on demand [here](https://openssf.org/resources/tech-talks/slsa/).

**Comment by lehors** [comment]
@afmarcum I'm not sure Melba will respond so I'll do it for her: we can close this.
